[package]
name = "php-deadscan"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
owo-colors = "4.2.3"
walkdir = "2.5.0"
tabled = "0.20.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"